# Generated by Django 2.2.12 on 2021-02-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0003_profile_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myId', models.IntegerField()),
                ('friendId', models.IntegerField()),
            ],
        ),
    ]
