# Generated by Django 2.2.12 on 2021-02-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0004_friendtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkMessageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('fromuser', models.IntegerField()),
                ('touser', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
