# Generated by Django 2.2.12 on 2021-03-05 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0005_talkmessagelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkmessagelist',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 5, 17, 55, 58, 378394)),
        ),
    ]
